### ISSUE TITLE
Missing wheels for macOS Monterey M1 - greenlet

### ISSUE THREAD

**Issue by georgik** [espressif/idf-python-wheels#5]
It seems that wheels for macOS Monterey M1 are missing at https://dl.espressif.com/pypi

How to simulate:
- clone: https://github.com/georgik/rustzx-esp32
- run native build: `cargo +esp-1.56.0.1 build --target xtensa-esp32s2-espidf --release --features "esp32s3_usb_otg native"`
- run pio build: `cargo +esp-1.56.0.1 build --target xtensa-esp32s2-espidf --release --features "esp32s3_usb_otg"`
- root cause: build of greenlet fails
- expected behaviour: greenlet should be installed from pypi as wheel

Failure for native build:
```
      copying src/greenlet/tests/_test_extension_cpp.cpp -> build/lib.macosx-12-arm64-3.9/greenlet/tests
      running build_ext
      building 'greenlet._greenlet' extension
      creating build/temp.macosx-12-arm64-3.9
      creating build/temp.macosx-12-arm64-3.9/src
      creating build/temp.macosx-12-arm64-3.9/src/greenlet
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/python_env/idf4.3_py3.9_env/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/greenlet/greenlet.c -o build/temp.macosx-12-arm64-3.9/src/greenlet/greenlet.o
      In file included from src/greenlet/greenlet.c:11:
      In file included from src/greenlet/greenlet.h:8:
      /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/Python.h:25:10: fatal error: 'stdio.h' file not found
      #include <stdio.h>
               ^~~~~~~~~
      1 error generated.
      error: command '/Users/georgik/.espressif/tools/xtensa-esp32-elf-clang/esp-12.0.1-20210823-aarch64-apple-darwin/bin/clang' failed with exit code 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/python_env/idf4.3_py3.9_env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lq/rjt6vbpn7kncx10ldq3h4v2w0000gn/T/pip-install-4vkv0g1y/greenlet_6e2cca41ea67474b8d573371f2419e8b/setup.py'"'"'; __file__='"'"'/private/var/folders/lq/rjt6vbpn7kncx10ldq3h4v2w0000gn/T/pip-install-4vkv0g1y/greenlet_6e2cca41ea67474b8d573371f2419e8b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/lq/rjt6vbpn7kncx10ldq3h4v2w0000gn/T/pip-record-trmz_xmy/install-record.txt --single-version-externally-managed --compile --install-headers /Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/python_env/idf4.3_py3.9_env/include/site/python3.9/greenlet Check the logs for full command output.
  WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
  You should consider upgrading via the '/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/python_env/idf4.3_py3.9_env/bin/python -m pip install --upgrade pip' command.
  Traceback (most recent call last):
    File "/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/esp-idf-v4.3.1/tools/idf_tools.py", line 1675, in <module>
      main(sys.argv[1:])
    File "/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/esp-idf-v4.3.1/tools/idf_tools.py", line 1671, in main
      action_func(args)
    File "/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/esp-idf-v4.3.1/tools/idf_tools.py", line 1396, in action_install_python_env
      subprocess.check_call(run_args, stdout=sys.stdout, stderr=sys.stderr)
    File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/python_env/idf4.3_py3.9_env/bin/python', '-m', 'pip', 'install', '--no-warn-script-location', '-r', '/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/esp-idf-v4.3.1/requirements.txt', '--extra-index-url', 'https://dl.espressif.com/pypi']' returned non-zero exit status 1.
  Error: Could not install esp-idf

  Caused by:
      Command '"python3" "/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/esp-idf-v4.3.1/tools/idf_tools.py" "--idf-path" "/Users/georgik/projects/rustzx-esp32-original/.embuild/espressif/esp-idf-v4.3.1" "--quiet" "--non-interactive" "install-python-env"' failed with exit code Some(1).
```

Failure for pio build:
```
  The following Python requirements are not satisfied:
  pyserial>=3.0
  future>=0.15.2
  cryptography>=2.1.4
  pyparsing>=2.0.3,<2.4.0
  pyelftools>=0.22
  gdbgui==0.13.2.0
  pygdbmi<=0.9.0.2
  kconfiglib==13.7.1
  reedsolo>=1.5.3,<=1.5.4
  bitstring>=3.1.6
  ecdsa>=0.16.0
  construct==2.10.54
  Please follow the instructions found in the "Set up the tools" section of ESP-IDF Getting Started Guide
  Diagnostic information:
      IDF_PYTHON_ENV_PATH: (not set)
      Python interpreter used: /Users/georgik/projects/rustzx-esp32/.embuild/espressif/python_env/idf4.3_py3.9_env/bin/python
      Warning: python interpreter not running from IDF_PYTHON_ENV_PATH
      PATH: /Users/georgik/projects/rustzx-esp32/.embuild/espressif/esp-idf-v4.3.1/tools:/Users/georgik/projects/rustzx-esp32/.embuild/espressif/python_env/idf4.3_py3.9_env/bin:/Users/georgik/projects/rustzx-esp32/.embuild/espressif/tools/xtensa-esp32s2-elf/esp-2021r1-8.4.0/xtensa-esp32s2-elf/bin:/Users/georgik/projects/rustzx-esp32/.embuild/espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/Users/georgik/.cargo/bin:/Users/georgik/.espressif/tools/xtensa-esp32-elf-clang/esp-12.0.1-20210823-aarch64-apple-darwin/bin/:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/georgik/.cargo/bin
  -- Configuring incomplete, errors occurred!
  See also "/Users/georgik/projects/rustzx-esp32/target/xtensa-esp32s2-espidf/release/build/esp-idf-sys-bcc4d3f6c48dbe8f/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  error: patch failed: components/xtensa/stdatomic.c:133
  error: components/xtensa/stdatomic.c: patch does not apply
  CMake Error at /Users/georgik/projects/rustzx-esp32/.embuild/espressif/esp-idf-v4.3.1/tools/cmake/build.cmake:277 (message):
    Some Python dependencies must be installed.  Check above message for
    details.
  Call Stack (most recent call first):
    /Users/georgik/projects/rustzx-esp32/.embuild/espressif/esp-idf-v4.3.1/tools/cmake/build.cmake:406 (__build_check_python)
    CMakeLists.txt:6 (idf_build_process)


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /Users/georgik/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.46/src/lib.rs:974:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by georgik** [comment]
There are two things that should be solved:
1. publish greenlet wheel for Python 3.9 aarch64 to dl.espressif.com/pypi
2. embuild should use system clang, not the clang from ESP-IDF, that causes the failure when building the wheel from the source.
